'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1
<<<<<<< Updated upstream

  '''<summary>
  '''form1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''mic123 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
<<<<<<< HEAD
  Protected WithEvents SM As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''ab control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ab As Global.MTCheckbox.MTCheckbox
=======
>>>>>>> Stashed changes
=======
  Protected WithEvents mic123 As Global.System.Web.UI.WebControls.GridView
>>>>>>> 1dbf0b41ced2bd58aac1b0d3d47a53812548188d
End Class
